
version: 2

models:
  - name: our_first_databse_order
    description: "A starter dbt model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: ord_status
        tests:
          - accepted_values:
              values:
               - success
               - Failure
               - Pending
               - failure
               - pending
               

  - name: our_first_databse_customer
    description: "A starter dbt model"
    columns:
      - name: cust_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  

  
