
version: 2

models:
  - name: our_first_databse_order
    description: "A starter dbt model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique

  - name: our_first_databse_customer
    description: "A starter dbt model"
    columns:
      - name: cust_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
  

  
