version: 2

models:
  - name: our_first_databse_order
    description: "A starter dbt model"
    tables:
       - name: customer
          columns:
           - name: customer_id
             description: Primary key of the table
             tests:
              - unique
              - not_null
       - name: order_data
          columns:
            - name: order__id
              description: Primary key of the table
              tests:
               - unique
               - not_null

           - name: cust_id
             description: Foreign key to customers

           - name: ord_status
             tests:
              - accepted_values:
                  values: ['Placed', 'Shipped', 'Completed', 'return_pending', 'returned']


