version: 2

models:
  - name: stg_customers
    description: "A starter dbt model"
    columns:
        - name: customer_id
          description: Primary key of the table
          tests:
            - unique
            - not_null
  - name: stg_order
    description: "A starter dbt model"
    columns:
        - name: order_id
          description: Primary key of the table
          tests:
            - unique
            - not_null


           



       