version: 2

models:
  - name: stg_customers
    description: "A starter dbt model"
    columns:
        - name: Customer_ID
          description: Primary key of the table
          tests:
            - unique
            - not_null


           



       
