version : 2
sources: 
    
    name: main
    meta:
      external_location: '/root/.dbt/northwind.duckdb'



    tables:
      - name: Customers
      - name: Employees
     
    

       
    
     
