version : 2
sources: 
    name: main
    schema: main
    meta:
      external_location: '/root/.dbt/external-1/northwind.duckdb'
      
    tables:
      - name: Customers
      - name: Employees
     
    

       
    
     
