version : 2
sources: 
  - name : public
    freshness:
      warn_after: {count: 12,period: hour}
      error_after: {count: 24,period: hour}

    loaded_at_field: _etl_loaded_at

    tables:
     - name: customer
     - name: order_data
     - name: payment
       freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
          # Apply a where clause in the freshness query
          filter: datediff('day', _etl_loaded_at, current_timestamp) < 2

       
    
     